### ISSUE TITLE
Remote Control server auth is insecure

### ISSUE THREAD

**Issue by gonzoblue** [mfcallahan/FreeSCAN#6]
Scanner > Control Scanner > Start Virtual Control > Remote Control Setup > Users

The authentication for the remote scanner control server is done in the client, not on the server. This is inherently insecure and misleading to the users of this feature. I suggest removing the user/auth portion entirely and simply suggest people put their remote control behind a firewall, or let them expose it to the internet and understand that it is not secure (this is what I do), or properly add an auth method that is controlled by the server. I found this when creating my [Android app](https://play.google.com/store/apps/details?id=appinventor.ai_GonzoFederation.RemoteFS) for Freescan.

**Comment by mfcallahan** [comment]
Hi @gonzoblue  - I'm very sorry for such a long delay in reply, but I decided to not actively maintain this repository a while ago. I am hosting it only for archival purposes, but I do encourage anyone who is interested to maintain their own fork of this repo. I will be closing this issue.
