### ISSUE TITLE
Enhancements To Blind Friendly Mode

### ISSUE THREAD

**Issue by pdevasto** [mfcallahan/FreeSCAN#8]
I am totally blind and own BCD325P2 and BCD996P2 scanners. Freescan is the only program I can use to set these radios up, and it has been INVALUABLE to me! Blind Friendly mode, in particular, has helped me tremendously. My issue: I use keyboard navigation (TAB/Shift+TAB) to move from field to field in edit screens. However, my screen readers do not announce field labels, they just say "button",  so I am not always sure I am editing the correct item. Can something be done to improve this situation?

**Comment by mfcallahan** [comment]
Hi @pdevasto - I'm very sorry for such a long delay in reply, but I decided to not actively maintain this repository a while ago. I am hosting it only for archival purposes, but I do encourage anyone to maintain your own fork. I will be closing this issue.
