### ISSUE TITLE
modus am auto 

### ISSUE THREAD

**Issue by fiann21** [mfcallahan/FreeSCAN#9]
plz fix am modus jumps always back to auto modus  (bug)

**Comment by mfcallahan** [comment]
Hi @fiann21, thanks for commenting. Unfortunately this repository is hosted only for archival purposes, and although I am the repo owner, I am not currently involved in any active development on FreeSCAN. I will close this issue, but I do encourage anyone who is interested to clone the repository - I have confirmed the main branch is stable and up to date with the latest version, and will build & run in Visual Studio.
